### ISSUE TITLE
Test BackHub 

### ISSUE THREAD

**Issue by matanec** [scopetech/scope-sandbox#1]
Test backup issue on public github project

**Comment by matanec** [comment]
I'm so pretty
![me](https://cloud.githubusercontent.com/assets/3167692/7134378/047f37fe-e2a5-11e4-984f-69d45b5c612a.jpg)

isn't in

**Comment by syways** [comment]
Yes you are

**Comment by matanec** [comment]
| Propety | Type | Nullable | Store Pattern | Max Length | Fixed Length | Unicode | Precision | Scale | Description |
|---|---|---|---|---|---|---|
|	Id	|	Int32	|	FALSE	|	Identity	|		|		|		|		|	
|	PolicyVehicleUnitId	|	Int32	|	FALSE	|		|		|		|		|		|	
|	DateCreated	|	DateTimeOffset	|	FALSE	|		|		|		|		|		|	
|	AccidentId	|	Int64	|	FALSE	|		|		|		|		|		|	
|	UnitSerialNumber	|	String	|	FALSE	|		|	20	|	FALSE	|	TRUE	|		|	
|	EventDateTime	|	DateTimeOffset	|	FALSE	|		|		|		|		|		|	
|	EventLocationGeoDataLatitude	|	Decimal	|		|		|		|		|		|	18	|	2
|	EventLocationGeoDataLongitude	|	Decimal	|		|		|		|		|		|	18	|	2
|	GeoDataLatitudeXBeforeAccident	|	Decimal	|		|		|		|		|		|	18	|	2
|	GeoDataLongitudeXBeforeAccident	|	Decimal	|		|		|		|		|		|	18	|	2
|	GeoDataLatitude45SecAfterAccident	|	Decimal	|		|		|		|		|		|	18	|	2
|	GeoDataLongitude45SecAfterAccident	|	Decimal	|		|		|		|		|		|	18	|	2
|	DrivingDirection	|	Int32	|		|		|		|		|		|		|	
|	SpeedAtEventTime	|	Decimal	|		|		|		|		|		|	18	|	2
|	MaxGForce	|	Decimal	|	FALSE	|		|		|		|		|	18	|	2
|	ImpactZones	|	String	|	FALSE	|		|	50	|	FALSE	|	TRUE	|		|	
|	ImpactAngle	|	Int32	|	FALSE	|		|		|		|		|		|	
|	ImpactSeverity	|	String	|	FALSE	|		|	50	|	FALSE	|	TRUE	|		|	
|	ImpactMagnitude	|	String	|	FALSE	|		|	50	|	FALSE	|	TRUE	|		|

**Comment by matanec** [comment]
no it is not ready
