### ISSUE TITLE
Test BackHub issue created by Syways

### ISSUE THREAD

**Issue by syways** [scopetech/scope-sandbox#2]
I also want to test BackHub

**Comment by syways** [comment]
Some Markup How to get user contact data
============================
This is step by step tutorial on how to get user phone and email, having only username. This can be useful for BKI Information system (BKI IS) when it fetched notification from insurance portal and want to froward it to portal users.
Tutorial audience is BKI IT Developers.
We assume you have table in BKI IS for storing portal users with its phones and emails, further I will call it BKI-Users

Let's imagine you've fetched notification which contain 2 NotificationFields called UserName, their values are:
1. Mat
2. David

**First let's process "Mat".**
Check if BKI-Users already contain record for this user, if yes use phone and email from that record to forward notification.
If there is no such record call for PolicyVehicleUnit info for user
>https://bki-stg.driveprofiler.net/bki/odata/Users?$filter=UserName eq 'Mat'&$expand=PolicyVehicleUnitUsers($expand=PolicyVehicleUnit)

**Comment by matanec** [comment]
cool

**Comment by syways** [comment]
I can make it cooler

**Comment by matanec** [comment]
do it

**Comment by syways** [comment]
ok I don't want

**Comment by AngryVinni** [comment]
swag
